CREATE OR REPLACE VIEW stats_report_24h AS
SELECT sc.service_id as 'service_id', sc.country_id as 'country_id',
(SELECT DISTINCT sc.id FROM report r WHERE sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'id',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 24 hour) AND date_sub(NOW(), INTERVAL 23 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice1',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 23 hour) AND date_sub(NOW(), INTERVAL 22 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice2',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 22 hour) AND date_sub(NOW(), INTERVAL 21 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice3',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 21 hour) AND date_sub(NOW(), INTERVAL 20 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice4',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 20 hour) AND date_sub(NOW(), INTERVAL 19 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice5',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 19 hour) AND date_sub(NOW(), INTERVAL 18 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice6',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 18 hour) AND date_sub(NOW(), INTERVAL 17 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice7',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 17 hour) AND date_sub(NOW(), INTERVAL 16 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice8',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 16 hour) AND date_sub(NOW(), INTERVAL 15 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice9',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 15 hour) AND date_sub(NOW(), INTERVAL 14 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice10',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 14 hour) AND date_sub(NOW(), INTERVAL 13 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice11',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 13 hour) AND date_sub(NOW(), INTERVAL 12 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice12',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 12 hour) AND date_sub(NOW(), INTERVAL 11 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice13',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 11 hour) AND date_sub(NOW(), INTERVAL 10 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice14',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 10 hour) AND date_sub(NOW(), INTERVAL 9 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice15',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 9 hour) AND date_sub(NOW(), INTERVAL 8 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice16',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 8 hour) AND date_sub(NOW(), INTERVAL 7 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice17',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 7 hour) AND date_sub(NOW(), INTERVAL 6 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice18',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 6 hour) AND date_sub(NOW(), INTERVAL 5 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice19',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 5 hour) AND date_sub(NOW(), INTERVAL 4 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice20',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 4 hour) AND date_sub(NOW(), INTERVAL 3 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice21',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 3 hour) AND date_sub(NOW(), INTERVAL 2 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice22',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 2 hour) AND date_sub(NOW(), INTERVAL 1 hour) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice23',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 1 hour) AND date_sub(NOW(), INTERVAL 0 minute) AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'slice24',
(SELECT count(*) FROM report r WHERE r.submittedAt BETWEEN date_sub(NOW(), INTERVAL 24 hour) AND NOW() AND sc.service_id = r.service_id AND sc.country_id = r.country_id) as 'totalReport'
FROM service_countries sc
WHERE EXISTS (SELECT * FROM report r WHERE sc.service_id = r.service_id AND sc.country_id = r.country_id);