version: '3.3'

services:
  db:
    image: mysql:8.0.29
    container_name: db_mysql_container
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    command: ["--log_bin_trust_function_creators=1"]
    ports:
      - 8001
  api:
    build: .
    container_name: django_container
    command: bash -c "python manage.py check_db mysql db 3306 &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
      - 8001:3306
    links:
      - api
      - db
    depends_on:
      - api