# ----------------------------------------------------------------
#          Service Down / IaC / Docker Compose / API
# @Version: 0.8
# ----------------------------------------------------------------
version: '3.3'

# ----------------------------------------------------------------
#                    Services
# ----------------------------------------------------------------
services:
  db:
    image: mysql:8.0.29
    container_name: db_mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    command: ["--log_bin_trust_function_creators=1"]
    volumes:
      - bd-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

  api:
    build: .
    container_name: django_container
    restart: always
    command: bash -c "python manage.py check_db mysql db 3306 &&
                      python manage.py migrate &&
                      python manage.py loadfixtures &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    build: ./nginx
    container_name: nginx_container
    restart: always
    volumes:
      - certibot_vol-www:/var/www/certbot/:ro
      - certibot_vol-conf:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - db
    depends_on:
      - api

  certibot:
    image: certbot/certbot
    container_name: certibot
    depends_on:
      - nginx
    volumes:
      - certibot_vol-www:/var/www/certbot/:rw
      - certibot_vol-conf:/etc/letsencrypt/:rw

# ----------------------------------------------------------------
#                    Volumes
# ----------------------------------------------------------------
volumes:
  bd-mysql:

  certibot_vol-www:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './nginx/certibot/www/'

  certibot_vol-conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './nginx/certibot/conf/'

# ----------------------------------------------------------------
#                    Networks
# ----------------------------------------------------------------
