# Generated by Django 4.0.4 on 2022-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=2, null=True)),
                ('domainSuffix', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=300, null=True)),
                ('path', models.URLField(max_length=100)),
                ('countries.json', models.ManyToManyField(to='api.country')),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
