# Generated by Django 4.0.4 on 2022-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_country_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='countries.json',
            new_name='countries',
        ),
        migrations.AddField(
            model_name='service',
            name='twitterUsername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
