# Generated by Django 4.0.4 on 2022-05-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='isAvailable',
            field=models.BooleanField(default=False),
        ),
    ]
