# Generated by Django 4.0.4 on 2022-08-08 17:24
import os

from django.db import connection, migrations


def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), 'sql/', filename)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


create_views_h1 = lambda _, __: load_data_from_sql('view_report_1h.sql')


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_report'),
    ]

    operations = [
        migrations.RunSQL("DROP VIEW IF EXISTS stats_report_1h;"),
        migrations.RunPython(create_views_h1),
    ]
