# Generated by Django 4.0.4 on 2022-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_statsreport1h'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsReport24H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalReport', models.IntegerField(db_column='totalReport')),
                ('interval24hours', models.IntegerField(db_column='slice1')),
                ('interval23hours', models.IntegerField(db_column='slice2')),
                ('interval22hours', models.IntegerField(db_column='slice3')),
                ('interval21hours', models.IntegerField(db_column='slice4')),
                ('interval20hours', models.IntegerField(db_column='slice5')),
                ('interval19hours', models.IntegerField(db_column='slice6')),
                ('interval18hours', models.IntegerField(db_column='slice7')),
                ('interval17hours', models.IntegerField(db_column='slice8')),
                ('interval16hours', models.IntegerField(db_column='slice9')),
                ('interval15hours', models.IntegerField(db_column='slice10')),
                ('interval14hours', models.IntegerField(db_column='slice11')),
                ('interval13hours', models.IntegerField(db_column='slice12')),
                ('interval12hours', models.IntegerField(db_column='slice13')),
                ('interval11hours', models.IntegerField(db_column='slice14')),
                ('interval10hours', models.IntegerField(db_column='slice15')),
                ('interval9hours', models.IntegerField(db_column='slice16')),
                ('interval8hours', models.IntegerField(db_column='slice17')),
                ('interval7hours', models.IntegerField(db_column='slice18')),
                ('interval6hours', models.IntegerField(db_column='slice19')),
                ('interval5hours', models.IntegerField(db_column='slice20')),
                ('interval4hours', models.IntegerField(db_column='slice21')),
                ('interval3hours', models.IntegerField(db_column='slice22')),
                ('interval2hours', models.IntegerField(db_column='slice23')),
                ('interval1hours', models.IntegerField(db_column='slice24')),
            ],
            options={
                'db_table': 'stats_report_24h',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='statsreport1h',
            table='stats_report_1h',
        ),
    ]
