# Generated by Django 4.0.4 on 2022-09-18 21:07
import os
import django.db.models.deletion

from django.db import migrations, models, connection


def load_data_from_sql(filename):
    file_path = os.path.join(os.path.dirname(__file__), 'sql/', filename)
    sql_statement = open(file_path).read()
    with connection.cursor() as c:
        c.execute(sql_statement)


create_trg_default_status = lambda _, __: load_data_from_sql('trg_default_status.sql')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.status')),
            ],
            options={
                'db_table': 'current_status',
            },
        ),
        migrations.RunSQL("ALTER TABLE `current_status` CHANGE `status_id` `status_id` BIGINT NOT NULL DEFAULT '1';"),
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_default_status"),
        migrations.RunPython(create_trg_default_status),
    ]
